PACKET_INDEX = {0: {'attrs': ['name', 'index', 'userid', 'networkid', 'address', 'bot'],
     'name': 'player_connect'},
 1: {'attrs': ['userid', 'reason', 'name', 'networkid', 'bot'],
     'name': 'player_disconnect'},
 2: {'attrs': ['userid'], 'name': 'player_activate'},
 3: {'attrs': ['userid', 'text'], 'name': 'player_say'},
 4: {'attrs': ['teamid', 'teamname'], 'name': 'team_info'},
 5: {'attrs': ['teamid', 'score'], 'name': 'team_score'},
 6: {'attrs': ['team', 'sound'], 'name': 'teamplay_broadcast_audio'},
 7: {'attrs': ['userid',
               'team',
               'oldteam',
               'disconnect',
               'autoteam',
               'silent',
               'name'],
     'name': 'player_team'},
 8: {'attrs': ['userid', 'class'], 'name': 'player_class'},
 9: {'attrs': ['teamonly', 'userid', 'text'], 'name': 'player_chat'},
 10: {'attrs': ['userid', 'kills', 'deaths', 'score'], 'name': 'player_score'},
 11: {'attrs': ['userid'], 'name': 'player_spawn'},
 12: {'attrs': ['userid', 'weapon', 'mode'], 'name': 'player_shoot'},
 13: {'attrs': ['userid', 'entity'], 'name': 'player_use'},
 14: {'attrs': ['userid', 'oldname', 'newname'], 'name': 'player_changename'},
 15: {'attrs': ['hintmessage'], 'name': 'player_hintmessage'},
 16: {'attrs': ['mapname'], 'name': 'game_newmap'},
 17: {'attrs': ['roundslimit', 'timelimit', 'fraglimit', 'objective'],
      'name': 'game_start'},
 18: {'attrs': ['winner'], 'name': 'game_end'},
 19: {'attrs': ['target', 'text'], 'name': 'game_message'},
 20: {'attrs': ['entindex', 'userid', 'material'], 'name': 'break_breakable'},
 21: {'attrs': ['entindex', 'userid'], 'name': 'break_prop'},
 22: {'attrs': ['entindex_killed',
                'entindex_attacker',
                'entindex_inflictor',
                'damagebits'],
      'name': 'entity_killed'},
 23: {'attrs': ['numadvanced', 'numbronze', 'numsilver', 'numgold'],
      'name': 'bonus_updated'},
 24: {'attrs': ['achievement_id', 'cur_val', 'max_val'],
      'name': 'achievement_increment'},
 25: {'attrs': ['entindex'], 'name': 'physgun_pickup'},
 26: {'attrs': ['entindex'], 'name': 'flare_ignite_npc'},
 27: {'attrs': ['vote_option', 'team', 'entityid'], 'name': 'vote_cast'},
 28: {'attrs': ['name', 'index', 'userid', 'networkid', 'bot'],
      'name': 'player_info'},
 29: {'attrs': ['userid',
                'attacker',
                'assister',
                'weapon',
                'headshot',
                'dominated',
                'revenge',
                'penetrated'],
      'name': 'player_death'},
 30: {'attrs': ['userid',
                'attacker',
                'health',
                'armor',
                'weapon',
                'dmg_health',
                'dmg_armor',
                'hitgroup'],
      'name': 'player_hurt'},
 31: {'attrs': ['userid', 'team', 'weapon'], 'name': 'item_purchase'},
 32: {'attrs': ['userid', 'site'], 'name': 'bomb_beginplant'},
 33: {'attrs': ['userid', 'site'], 'name': 'bomb_abortplant'},
 34: {'attrs': ['userid', 'site'], 'name': 'bomb_planted'},
 35: {'attrs': ['userid', 'site'], 'name': 'bomb_defused'},
 36: {'attrs': ['userid', 'site'], 'name': 'bomb_exploded'},
 37: {'attrs': ['userid', 'entindex'], 'name': 'bomb_dropped'},
 38: {'attrs': ['userid'], 'name': 'bomb_pickup'},
 39: {'attrs': ['entityid'], 'name': 'defuser_dropped'},
 40: {'attrs': ['entityid', 'userid'], 'name': 'defuser_pickup'},
 41: {'attrs': [], 'name': 'announce_phase_end'},
 42: {'attrs': [], 'name': 'cs_intermission'},
 43: {'attrs': ['userid', 'haskit'], 'name': 'bomb_begindefuse'},
 44: {'attrs': ['userid'], 'name': 'bomb_abortdefuse'},
 45: {'attrs': ['userid', 'hostage'], 'name': 'hostage_follows'},
 46: {'attrs': ['userid', 'hostage'], 'name': 'hostage_hurt'},
 47: {'attrs': ['userid', 'hostage'], 'name': 'hostage_killed'},
 48: {'attrs': ['userid', 'hostage', 'site'], 'name': 'hostage_rescued'},
 49: {'attrs': ['userid', 'hostage'], 'name': 'hostage_stops_following'},
 50: {'attrs': [], 'name': 'hostage_rescued_all'},
 51: {'attrs': ['hostage'], 'name': 'hostage_call_for_help'},
 52: {'attrs': ['userid'], 'name': 'vip_escaped'},
 53: {'attrs': ['userid', 'attacker'], 'name': 'vip_killed'},
 54: {'attrs': ['userid', 'slot'], 'name': 'player_radio'},
 55: {'attrs': ['entindex'], 'name': 'bomb_beep'},
 56: {'attrs': ['userid', 'weapon', 'silenced'], 'name': 'weapon_fire'},
 57: {'attrs': ['userid', 'weapon'], 'name': 'weapon_fire_on_empty'},
 58: {'attrs': ['userid'], 'name': 'weapon_outofammo'},
 59: {'attrs': ['userid'], 'name': 'weapon_reload'},
 60: {'attrs': ['userid'], 'name': 'weapon_zoom'},
 61: {'attrs': ['userid'], 'name': 'silencer_detach'},
 62: {'attrs': ['userid'], 'name': 'inspect_weapon'},
 63: {'attrs': ['userid'], 'name': 'weapon_zoom_rifle'},
 64: {'attrs': ['userid', 'inrestart'], 'name': 'player_spawned'},
 65: {'attrs': ['userid', 'item'], 'name': 'item_pickup'},
 66: {'attrs': ['userid', 'item', 'index'], 'name': 'ammo_pickup'},
 67: {'attrs': ['userid',
                'item',
                'canzoom',
                'hassilencer',
                'issilenced',
                'hastracers',
                'weptype',
                'ispainted'],
      'name': 'item_equip'},
 68: {'attrs': ['userid', 'canbuy'], 'name': 'enter_buyzone'},
 69: {'attrs': ['userid', 'canbuy'], 'name': 'exit_buyzone'},
 70: {'attrs': [], 'name': 'buytime_ended'},
 71: {'attrs': ['userid', 'hasbomb', 'isplanted'], 'name': 'enter_bombzone'},
 72: {'attrs': ['userid', 'hasbomb', 'isplanted'], 'name': 'exit_bombzone'},
 73: {'attrs': ['userid'], 'name': 'enter_rescue_zone'},
 74: {'attrs': ['userid'], 'name': 'exit_rescue_zone'},
 75: {'attrs': ['userid'], 'name': 'silencer_off'},
 76: {'attrs': ['userid'], 'name': 'silencer_on'},
 77: {'attrs': ['userid'], 'name': 'buymenu_open'},
 78: {'attrs': ['userid'], 'name': 'buymenu_close'},
 79: {'attrs': [], 'name': 'round_prestart'},
 80: {'attrs': [], 'name': 'round_poststart'},
 81: {'attrs': ['timelimit', 'fraglimit', 'objective'], 'name': 'round_start'},
 82: {'attrs': ['winner', 'reason', 'message'], 'name': 'round_end'},
 83: {'attrs': ['userid'], 'name': 'grenade_bounce'},
 84: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'],
      'name': 'hegrenade_detonate'},
 85: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'],
      'name': 'flashbang_detonate'},
 86: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'],
      'name': 'smokegrenade_detonate'},
 87: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'],
      'name': 'smokegrenade_expired'},
 88: {'attrs': ['userid', 'x', 'y', 'z'], 'name': 'molotov_detonate'},
 89: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'],
      'name': 'decoy_detonate'},
 90: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'], 'name': 'decoy_started'},
 91: {'attrs': ['entityid', 'x', 'y', 'z'], 'name': 'inferno_startburn'},
 92: {'attrs': ['entityid', 'x', 'y', 'z'], 'name': 'inferno_expire'},
 93: {'attrs': ['entityid', 'x', 'y', 'z'], 'name': 'inferno_extinguish'},
 94: {'attrs': ['userid', 'entityid', 'x', 'y', 'z'], 'name': 'decoy_firing'},
 95: {'attrs': ['userid', 'x', 'y', 'z'], 'name': 'bullet_impact'},
 96: {'attrs': ['userid'], 'name': 'player_footstep'},
 97: {'attrs': ['userid'], 'name': 'player_jump'},
 98: {'attrs': ['userid'], 'name': 'player_blind'},
 99: {'attrs': ['userid', 'damage'], 'name': 'player_falldamage'},
 100: {'attrs': ['entindex', 'userid'], 'name': 'door_moving'},
 101: {'attrs': [], 'name': 'round_freeze_end'},
 102: {'attrs': [], 'name': 'mb_input_lock_success'},
 103: {'attrs': [], 'name': 'mb_input_lock_cancel'},
 104: {'attrs': ['area', 'blocked'], 'name': 'nav_blocked'},
 105: {'attrs': [], 'name': 'nav_generate'},
 106: {'attrs': ['forceupload'], 'name': 'player_stats_updated'},
 107: {'attrs': [], 'name': 'achievement_info_loaded'},
 108: {'attrs': ['userid'], 'name': 'spec_target_updated'},
 109: {'attrs': ['oldmode', 'newmode', 'obs_target'],
       'name': 'hltv_changed_mode'},
 110: {'attrs': [], 'name': 'cs_game_disconnected'},
 111: {'attrs': ['show_timer_defend',
                 'show_timer_attack',
                 'timer_time',
                 'final_event',
                 'funfact_token',
                 'funfact_player',
                 'funfact_data1',
                 'funfact_data2',
                 'funfact_data3'],
       'name': 'cs_win_panel_round'},
 112: {'attrs': [], 'name': 'cs_win_panel_match'},
 113: {'attrs': [], 'name': 'cs_match_end_restart'},
 114: {'attrs': [], 'name': 'cs_pre_restart'},
 115: {'attrs': ['victim',
                 'killer',
                 'hits_taken',
                 'damage_taken',
                 'hits_given',
                 'damage_given'],
       'name': 'show_freezepanel'},
 116: {'attrs': [], 'name': 'hide_freezepanel'},
 117: {'attrs': [], 'name': 'freezecam_started'},
 118: {'attrs': ['avenger_id', 'avenged_player_id'],
       'name': 'player_avenged_teammate'},
 119: {'attrs': ['player', 'achievement'], 'name': 'achievement_earned'},
 120: {'attrs': ['achievement', 'splitscreenplayer'],
       'name': 'achievement_earned_local'},
 121: {'attrs': ['player', 'quality', 'method', 'itemdef', 'itemid'],
       'name': 'item_found'},
 122: {'attrs': ['frags', 'max_rounds', 'win_rounds', 'time'],
       'name': 'match_end_conditions'},
 123: {'attrs': ['userid', 'reason'], 'name': 'round_mvp'},
 124: {'attrs': ['userid'], 'name': 'player_decal'},
 125: {'attrs': ['full_reset'], 'name': 'teamplay_round_start'},
 126: {'attrs': [], 'name': 'client_disconnect'},
 127: {'attrs': ['numPlayers',
                 'numSpectators',
                 'avg_rank',
                 'numTSlotsFree',
                 'numCTSlotsFree'],
       'name': 'switch_team'},
 128: {'attrs': [], 'name': 'write_profile_data'},
 129: {'attrs': [], 'name': 'update_matchmaking_stats'},
 130: {'attrs': ['userid', 'vote'], 'name': 'player_reset_vote'},
 131: {'attrs': ['enable'], 'name': 'enable_restart_voting'},
 132: {'attrs': ['action', 'data', 'slot'], 'name': 'sfuievent'},
 133: {'attrs': ['userid', 'type', 'vote_parameter'], 'name': 'start_vote'},
 134: {'attrs': ['userid'], 'name': 'player_given_c4'},
 135: {'attrs': ['userid'], 'name': 'tr_player_flashbanged'},
 136: {'attrs': ['complete'], 'name': 'tr_mark_complete'},
 137: {'attrs': ['time'], 'name': 'tr_mark_best_time'},
 138: {'attrs': [], 'name': 'tr_exit_hint_trigger'},
 139: {'attrs': ['userid', 'botid', 'index'], 'name': 'bot_takeover'},
 140: {'attrs': ['userid'], 'name': 'tr_show_finish_msgbox'},
 141: {'attrs': ['userid'], 'name': 'tr_show_exit_msgbox'},
 142: {'attrs': [], 'name': 'reset_player_controls'},
 143: {'attrs': ['userid', 'reason'], 'name': 'jointeam_failed'},
 144: {'attrs': ['userid', 'toteam'], 'name': 'teamchange_pending'},
 145: {'attrs': [], 'name': 'material_default_complete'},
 146: {'attrs': ['next'], 'name': 'cs_prev_next_spectator'},
 147: {'attrs': ['eventtype', 'eventdata'], 'name': 'cs_handle_ime_event'},
 148: {'attrs': ['nextlevel'], 'name': 'nextlevel_changed'},
 149: {'attrs': ['player', 'category', 'rank'], 'name': 'seasoncoin_levelup'}}